export type RockBag = { [key: string]: { first: boolean, second: boolean } };

export const bagState = {
    strangeRocks: {
        agility: { first: false, second: false },
        construction: { first: false, second: false },
        cooking: { first: false, second: false },
        crafting: { first: false, second: false },
        farming: { first: false, second: false },
        firemaking: { first: false, second: false },
        fishing: { first: false, second: false },
        fletching: { first: false, second: false },
        herblore: { first: false, second: false },
        hunter: { first: false, second: false },
        mining: { first: false, second: false },
        runecrafting: { first: false, second: false },
        smithing: { first: false, second: false },
        thieving: { first: false, second: false },
        woodcutting: { first: false, second: false },
    },
    goldenRocks: {
        agility: { first: false, second: false },
        construction: { first: false, second: false },
        crafting: { first: false, second: false },
        divination: { first: false, second: false },
        dungeoneering: { first: false, second: false },
        farming: { first: false, second: false },
        herblore: { first: false, second: false },
        magic: { first: false, second: false },
        melee: { first: false, second: false },
        mining: { first: false, second: false },
        prayer: { first: false, second: false },
        ranged: { first: false, second: false },
        slayer: { first: false, second: false },
        smithing: { first: false, second: false },
        summoning: { first: false, second: false },
        woodcutting: { first: false, second: false },
    },
};
